### ISSUE TITLE
compile error on importing kmer

### ISSUE THREAD

**Issue by monkollek** [brentp/indelope#6]
Running the compile command: nim c -d:release src/indelope

indelope.nim(15, 8) Error: cannot open 'kmer'

due to the import kmer command on https://github.com/brentp/indelope/blob/master/src/indelope.nim#L15

Is the kmer.nim file missing or dependency undefined in the .nimble file?

**Comment by brentp** [comment]
thanks for reporting. for now, you'll have to get this from:

https://github.com/brentp/nim-kmer 

and run nimble install from that directory. I'll get this into nim packages so that it's `nimble install`able soon and address more of these installation problems this week.
let me know if you hit anything else.

**Comment by monkollek** [comment]
All good, compiler error regarding kmer gone. thanks for the fast response!

**Comment by brentp** [comment]
Cheers.
this is also now part of the .nimble file and will be in the package index soon: https://github.com/nim-lang/packages/pull/629
